# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-03-01 07:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_index', models.IntegerField(db_column='item_number', default=10000, verbose_name='项目索引')),
                ('item_chinese_name', models.CharField(db_column='item_chinese_name', max_length=20, verbose_name='项目中文名称')),
                ('item_english_name', models.CharField(db_column='item_english_name', max_length=20, verbose_name='项目英文名称')),
                ('item_method', models.CharField(db_column='item_method', max_length=20, verbose_name='检测方法')),
                ('is_calc', models.BooleanField(db_column='is_calc', default=False, verbose_name='是否计算项目')),
                ('is_use', models.BooleanField(db_column='is_use', default=False, verbose_name='是否使用')),
            ],
            options={
                'verbose_name': '项目信息',
                'verbose_name_plural': '项目信息',
                'db_table': 'item',
                'ordering': ['item_index'],
            },
        ),
        migrations.CreateModel(
            name='ItemRefference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(db_column='is_default', default=False, verbose_name='是否默认')),
                ('gender', models.CharField(blank=True, choices=[('M', '男'), ('F', '女')], db_column='gender', max_length=5, verbose_name='性别')),
                ('start_age', models.IntegerField(blank=True, db_column='start_age', null=True, verbose_name='开始年龄')),
                ('end_age', models.IntegerField(blank=True, db_column='end_age', null=True, verbose_name='结束年龄')),
                ('age_unit', models.CharField(blank=True, choices=[('1', '岁'), ('2', '月'), ('3', '天')], db_column='age_unit', max_length=10, verbose_name='年龄类型')),
                ('ref_low', models.DecimalField(blank=True, db_column='ref_low', decimal_places=3, max_digits=10, null=True, verbose_name='参考低限')),
                ('ref_high', models.DecimalField(blank=True, db_column='ref_high', decimal_places=3, max_digits=10, null=True, verbose_name='参考高限')),
                ('item_id', models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, to='item.Item', verbose_name='项目ID')),
            ],
            options={
                'verbose_name': '项目参考值信息',
                'verbose_name_plural': '项目参考值信息',
                'db_table': 'itemrefference',
                'ordering': ['item_id'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_index', models.IntegerField(db_column='unit_index', default=1001, verbose_name='单位编号')),
                ('unit_name', models.CharField(db_column='unit_name', max_length=20, verbose_name='单位名称')),
            ],
            options={
                'verbose_name': '项目单位',
                'verbose_name_plural': '项目单位',
                'db_table': 'unit',
                'ordering': ['unit_index'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='item_unit',
            field=models.ForeignKey(db_column='item_unit', on_delete=django.db.models.deletion.CASCADE, to='item.Unit', verbose_name='项目单位'),
        ),
    ]
