# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-02-28 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import login.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_column='code', max_length=256, verbose_name='注册码')),
                ('c_time', models.DateTimeField(auto_now_add=True, db_column='c_time', verbose_name='注册时间')),
            ],
            options={
                'verbose_name': '确认码',
                'verbose_name_plural': '确认码',
                'ordering': ['-c_time'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=128, unique=True, verbose_name='用户名')),
                ('password', models.CharField(db_column='password', max_length=256, verbose_name='密码')),
                ('email', models.EmailField(db_column='email', max_length=254, unique=True, verbose_name='邮箱')),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], db_column='sex', default='男', max_length=32, verbose_name='性别')),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('has_confirmed', models.BooleanField(db_column='has_confirmed', default=False, verbose_name='邮件确认')),
                ('user_img', models.ImageField(blank=True, db_column='user_img', null=True, upload_to=login.models.user_directory_path, verbose_name='头像')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['-c_time'],
            },
        ),
        migrations.AddField(
            model_name='confirmstring',
            name='user',
            field=models.OneToOneField(db_column='user', on_delete=django.db.models.deletion.CASCADE, to='login.User', verbose_name='用户'),
        ),
    ]
