# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-03-01 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_auto_20200229_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_index', models.CharField(db_column='instrument_index', max_length=50, unique=True, verbose_name='设备编号')),
                ('instrument_name', models.CharField(db_column='instrument_name', max_length=50, verbose_name='设备名称')),
                ('instrument_status', models.CharField(choices=[('1', '正常'), ('2', '备用'), ('3', '故障'), ('4', '报废')], db_column='instrument_status', max_length=10, verbose_name='设备状态')),
                ('instrument_start_date', models.DateField(auto_now_add=True, db_column='instrument_start_date', verbose_name='启用时间')),
                ('instrument_company', models.ForeignKey(db_column='instrument_company', on_delete=django.db.models.deletion.CASCADE, to='company.Company', verbose_name='设备公司')),
                ('instrument_manager', models.ForeignKey(db_column='instrument_manager', on_delete=django.db.models.deletion.CASCADE, to='company.Employee', verbose_name='管理人员')),
            ],
            options={
                'verbose_name': '设备编号',
                'verbose_name_plural': '设备编号',
                'db_table': 'instrument',
                'ordering': ['instrument_index'],
            },
        ),
    ]
