# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-02-28 16:54
from __future__ import unicode_literals

import company.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_index', models.IntegerField(db_column='company_index', default=12, verbose_name='单位编号')),
                ('company_name', models.CharField(db_column='company_name', max_length=50, unique=True, verbose_name='单位名称')),
                ('company_address', models.CharField(db_column='company_address', max_length=50, verbose_name='单位地址')),
            ],
            options={
                'verbose_name': '单位名称',
                'verbose_name_plural': '单位名称',
                'db_table': 'company',
                'ordering': ['company_index'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_index', models.IntegerField(db_column='department_index', default=12, verbose_name='部门编号')),
                ('department_name', models.CharField(db_column='department_name', max_length=50, verbose_name='部门名称')),
                ('department_position', models.CharField(db_column='department_position', max_length=50, verbose_name='部门位置')),
                ('belong_company', models.ForeignKey(db_column='belong_company', on_delete=django.db.models.deletion.CASCADE, to='company.Company', verbose_name='单位名称')),
            ],
            options={
                'verbose_name': '部门名称',
                'verbose_name_plural': '部门名称',
                'db_table': 'department',
                'ordering': ['department_index'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_index', models.CharField(db_column='employee_index', max_length=20, unique=True, verbose_name='员工编号')),
                ('employee_name', models.CharField(db_column='employee_name', max_length=10, verbose_name='员工姓名')),
                ('employee_gender', models.CharField(choices=[('M', '男'), ('F', '女'), ('U', '不详')], db_column='employee_gender', max_length=10, verbose_name='员工姓别')),
                ('employee_telephone', models.CharField(db_column='employee_telephone', max_length=20, verbose_name='联系电话')),
                ('belong_department', models.ForeignKey(blank=True, db_column='belong_department', null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Company', verbose_name='所属部门')),
            ],
            options={
                'verbose_name': '员工信息',
                'verbose_name_plural': '员工信息',
                'db_table': 'employee',
                'ordering': ['employee_index'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_img', models.ImageField(blank=True, db_column='employee_img', null=True, upload_to=company.models.user_directory_path, verbose_name='头像')),
                ('employee_hire_date', models.DateTimeField(auto_now_add=True, db_column='employee_hire_date', verbose_name='入职时间')),
                ('is_delete', models.BooleanField(db_column='is_delete', default=False, verbose_name='是否离职')),
            ],
            options={
                'verbose_name': '员工详细信息',
                'verbose_name_plural': '员工详细信息',
                'db_table': 'employee_detail',
                'ordering': ['employee_index'],
            },
        ),
        migrations.CreateModel(
            name='LeadershipPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leadership_positon_name', models.CharField(db_column='pro_title_name', max_length=50, verbose_name='领导职务')),
            ],
            options={
                'verbose_name': '领导职务',
                'verbose_name_plural': '领导职务',
                'db_table': 'leadershipposition',
            },
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional_name', models.CharField(db_column='pro_name', max_length=50, verbose_name='专业名称')),
            ],
            options={
                'verbose_name': '专业名称',
                'verbose_name_plural': '专业名称',
                'db_table': 'professional',
            },
        ),
        migrations.CreateModel(
            name='ProfessionalTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional_title_name', models.CharField(db_column='pro_title_name', max_length=50, verbose_name='专业职称')),
            ],
            options={
                'verbose_name': '专业职称',
                'verbose_name_plural': '专业职称',
                'db_table': 'professionaltitle',
            },
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='belong_leadership_position',
            field=models.ForeignKey(blank=True, db_column='belong_leadership_position', null=True, on_delete=django.db.models.deletion.CASCADE, to='company.LeadershipPosition', verbose_name='领导职务'),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='belong_professional',
            field=models.OneToOneField(db_column='belong_professional', on_delete=django.db.models.deletion.CASCADE, to='company.Professional', verbose_name='专业名称'),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='belong_professional_title',
            field=models.OneToOneField(db_column='belong_professional_title', on_delete=django.db.models.deletion.CASCADE, to='company.ProfessionalTitle', verbose_name='专业职称'),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='employee_index',
            field=models.OneToOneField(db_column='employee_index', on_delete=django.db.models.deletion.CASCADE, to='company.Employee', verbose_name='员工编号'),
        ),
    ]
