# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-02-29 02:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='belong_department',
            field=models.ForeignKey(blank=True, db_column='belong_department', null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Department', verbose_name='所属部门'),
        ),
    ]
