# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-03-13 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_auto_20200229_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReasonCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_code', models.IntegerField(db_column='reason_code', default=12, verbose_name='原因代码')),
                ('reason_name', models.CharField(db_column='reason_name', max_length=50, verbose_name='原因名称')),
            ],
            options={
                'verbose_name': '原因名称',
                'verbose_name_plural': '原因名称',
                'db_table': 'reason_code',
                'ordering': ['reason_code'],
            },
        ),
        migrations.CreateModel(
            name='SpecimenType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specimen_type_index', models.IntegerField(db_column='specimen_type_index', default=12, verbose_name='样本类型编号')),
                ('specimen_type_name', models.CharField(db_column='specimen_type_name', max_length=50, verbose_name='样本类型名称')),
            ],
            options={
                'verbose_name': '样本类型',
                'verbose_name_plural': '样本类型',
                'db_table': 'specimen_type',
                'ordering': ['specimen_type_index'],
            },
        ),
        migrations.CreateModel(
            name='UnqualifiedSpecimen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unqualified_specimen_date', models.DateTimeField(auto_now_add=True, db_column='unqualified_specimen_date', verbose_name='日期-时间')),
                ('unqualified_specimen_name', models.CharField(db_column='unqualified_specimen_name', max_length=10, verbose_name='患者姓名')),
                ('medical_record_number', models.CharField(db_column='medical_record_no', max_length=10, verbose_name='病历号')),
                ('serial_number', models.CharField(db_column='serial_number', max_length=15, verbose_name='流水号')),
                ('bed_number', models.CharField(blank=True, db_column='bed_number', max_length=5, null=True, verbose_name='床号')),
                ('inspection_item', models.CharField(blank=True, db_column='inspection_item', max_length=15, null=True, verbose_name='检查项目')),
                ('reason_description', models.CharField(blank=True, db_column='reason_description', max_length=20, null=True, verbose_name='原因描述')),
                ('remarks', models.CharField(blank=True, db_column='remarks', max_length=50, null=True, verbose_name='备注')),
                ('department_name', models.ForeignKey(blank=True, db_column='department_name', null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Department', verbose_name='科室')),
                ('reason_code', models.ForeignKey(db_column='reason_code', on_delete=django.db.models.deletion.CASCADE, to='record.ReasonCode', verbose_name='原因代码')),
                ('recorder', models.ForeignKey(db_column='recorder', on_delete=django.db.models.deletion.CASCADE, related_name='recorder', to='company.Employee', verbose_name='记录者')),
                ('reporter', models.ForeignKey(db_column='reporter', on_delete=django.db.models.deletion.CASCADE, related_name='reporter', to='company.Employee', verbose_name='报告者')),
                ('specimen_type', models.ForeignKey(blank=True, db_column='specimen_type', null=True, on_delete=django.db.models.deletion.CASCADE, to='record.SpecimenType', verbose_name='标本类型')),
            ],
            options={
                'verbose_name': '不合格标本登记表',
                'verbose_name_plural': '不合格标本登记表',
                'db_table': 'unqualified_specimen',
                'ordering': ['unqualified_specimen_date'],
            },
        ),
    ]
